twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        app_version: '%env(APP_VERSION)%'

when@test:
    twig:
        strict_variables: true

when@dev:
    twig:
        cache: false
