name: Deploy to FTP

on:
  release:
    types: [published]

env:
  APP_ENV: prod
  APP_VERSION: ${{ github.ref_name }}

jobs:
  ftp_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: "--ignore-platform-reqs --optimize-autoloader --no-dev"
          
      - name: Create env.local.php
        run: |
          touch .env.local
          echo "APP_VERSION=\"${{ github.ref_name }}\"" >> .env.local
          echo "APP_DEBUG=0" >> .env.local
          echo "DATABASE_URL=\"${{ secrets.SYMFONY_DATABASE_URL }}\"" >> .env.local
          echo "MAILER_DSN=\"${{ secrets.SYMFONY_MAILER_DSN }}\"" >> .env.local
          composer dump-autoload --optimize --classmap-authoritative
          composer dump-env prod
      
      - name: Upload to hosting FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./com.d9beud.genealogist.app/
          log-level: 'minimal'
          exclude: |
            **/.git*
            **/.git*/**
            var/cache/**
